# Ruby dependencies for all Bazel web assets.

# For consistency, this file should be identical across docs.bazel.build,
# blog.bazel.build and www.bazel.build.
# TODO(https://github.com/bazelbuild/bazel/issues/10793): Extract into single source of truth.

gem 'jekyll', '~> 3.8.6'
gem 'jekyll-paginate', '~> 1.0'
gem 'pygments.rb', '~> 0.6.0'
gem 'redcarpet', '~> 3.2', '>= 3.2.3'
gem 'jekyll-toc', '~> 0.13.1'
gem 'jekyll-sitemap', '~> 1.4.0'
